USE Expert_Match;

ALTER TABLE session_messages
  ADD COLUMN IF NOT EXISTS message_status VARCHAR(20) NOT NULL DEFAULT 'sent',
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seen_at TIMESTAMP NULL DEFAULT NULL;
