USE Expert_Match;

ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS request_message VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS requested_at TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS declined_at TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS decline_reason VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ended_by_role VARCHAR(20) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ended_by_name VARCHAR(140) NULL DEFAULT NULL;
